#!/bin/bash
# BSD 3-clause licence by rfree@mempo.org (C) 2015 || mempo.org mempo.i2p
# Converts a dmesg output by adding file/line of kernel to any kernel traces - see usage below

function about_us {
	echo "lines_in_dmesg.sh"
	echo "See: https://github.com/mempo/mempo-scripts/ - look for script lines_in_dmesg.sh"
	echo "See: http://www.mempo.org (or .i2p)"
}

function usage {
	echo 
	echo "Usage: $0 msgfile objfile"
	echo "msgfile is the text file with output from dmesg"
	echo "objfile is the vmlinux (the uncompressed, not stripped vmlinux file generated while building kernel)"
	echo 
	echo "Converts a dmesg output by adding file/line of kernel to any kernel trace"
	echo "In example it will read text file containing lines:"
	echo "Jan 30 05:39:01 debian kernel: [64195.978547] Call Trace:"
	echo "Jan 30 05:39:01 debian kernel: [64195.978547]  [<ffffffff81039520>] __might_sleep+0xfc/0x10b"
	echo "Jan 30 05:39:01 debian kernel: [64195.978547]  [<ffffffff81140e53>] end_writeback+0x24/0xb6"
	echo "And will output lines with address translated to file:line of vmlinux kernel source code, like:"
	echo "[64195.978547] Call Trace: "
	echo "[64195.978547]   ffffffff81039520  __might_sleep+0xfc/0x10b  = /kernel/sched.c:8670"
	echo "[64195.978547]   ffffffff81140e53  end_writeback+0x24/0xb6  = /include/linux/spinlock.h:310"
	echo
	about_us
}

msgfile=$1
objfile=$2

[[ -r "$msgfile" ]] || { echo "ERROR: Can not read msgfile ($msgfile)" ; usage ; exit 1; }
[[ -r "$objfile" ]] || { echo "ERROR: Can not read objfile ($objfile)" ; usage ; exit 1; }

cat "$msgfile" | sed -e 's/^\(.*\)\[<\(.*\)>\]\(.*\)$/ADDRESS \2 \1 \2 \3/g' | while IFS= read -r line; do
#	echo "$line"
	read -r addrtag addr rest <<< "$line"
	if [[ "$addrtag" == "ADDRESS" ]] ; then
		codeline=$(addr2line -e kernel-build/linux-mempo/linux-3.2.66/vmlinux  $addr | sed -e 's/.*\/linux-[^/]*//g')
		info=" = $codeline"
		main="$rest"
	else
		info=""
		main="$line"
	fi
	main2=$( echo "$main" | sed -e 's/^... .. ..:..:.. [^ ]* [^ ]* //g' )
	echo "$main2 $info"
done

echo -n "Generated by: " ; about_us

